steps:
  - name: 'docker'
    args:
      [
        'build',
        '--tag',
        'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
        '--file',
        './docker/production/Dockerfile',
        '.',
      ]
    id: 'build-app'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['app', 'deploy', '--quiet']
    id: 'deploy-app'
    entrypoint: 'gcloud'

timeout: '12m'

options:
  logging: 'CLOUD_LOGGING_ONLY'

images:
  - 'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
